name: KernelSU Builder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libssl-dev

      - name: Sync KernelSU
        run: |
          git remote add kernelsu https://github.com/tiann/KernelSU || true
          git fetch kernelsu
          git merge kernelsu/main --allow-unrelated-histories || true

      - name: Build Kernel
        run: |
          make clean
          make <defconfig>
          make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: out/
